# Descriptives

Import statements and data

In [1]:
# Import statements
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle

In [2]:
filtered_donor_info = pd.read_csv('/Users/dionnespaltman/Desktop/V6/filtered_donor_info_03-06-2024.csv', sep=',')

if 'Unnamed: 0' in filtered_donor_info.columns:
    filtered_donor_info.drop(columns=['Unnamed: 0'], inplace=True)

display(filtered_donor_info)

,ID,Stage,Gender,Age,Date,Location,Condition,Weight,Length,Faintness,...,Nervousness,Physical_sum,Psychological_sum,Sum_VVR,Sum_12,Sum_456,Sum_4567,Sum_1,Sum_2,VVR_group
0,23,1.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,2.0,6.0,7.0,13.0,24.0,27.0,37.0,13.0,11.0,0
1,23,2.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,2.0,4.0,7.0,11.0,24.0,27.0,37.0,13.0,11.0,0
2,23,3.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,2.0,5.0,6.0,11.0,24.0,27.0,37.0,13.0,11.0,0
3,23,4.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,2.0,4.0,6.0,10.0,24.0,27.0,37.0,13.0,11.0,0
4,23,5.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,1.0,4.0,4.0,8.0,24.0,27.0,37.0,13.0,11.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,146,2.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,2.0,4.0,7.0,11.0,22.0,32.0,40.0,11.0,11.0,1
706,146,4.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,3.0,4.0,8.0,12.0,22.0,32.0,40.0,11.0,11.0,1
707,146,5.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,1.0,5.0,5.0,10.0,22.0,32.0,40.0,11.0,11.0,1
708,146,6.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,1.0,5.0,5.0,10.0,22.0,32.0,40.0,11.0,11.0,1
709,146,7.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,1.0,4.0,4.0,8.0,22.0,32.0,40.0,11.0,11.0,1

# Get the range of dates

In [3]:
# Find the first and last dates
first_date = filtered_donor_info['Date'].min()
last_date = filtered_donor_info['Date'].max()

print("First date:", first_date)
print("Last date:", last_date)

First date: 2020-01-22
Last date: 2021-12-05

# Counts

In [6]:
# Ensure each ID is unique by dropping duplicates based on 'ID'
unique_donor_info = filtered_donor_info.drop_duplicates(subset='ID')

# Count occurrences of VVR_group
vvr_group_counts = unique_donor_info['VVR_group'].value_counts()
print("\nVVR_group counts (per unique ID):\n", vvr_group_counts)

# Count occurrences of Condition
condition_counts = unique_donor_info['Condition'].value_counts()
print("\nCondition counts (per unique ID):\n", condition_counts)

# Count occurrences of Gender
gender_counts = unique_donor_info['Gender'].value_counts()
print("\nGender counts (per unique ID):\n", gender_counts)

VVR_group counts (per unique ID):
 0    74
1    37
Name: VVR_group, dtype: int64

Condition counts (per unique ID):
 1    60
3    32
2    19
Name: Condition, dtype: int64

Gender counts (per unique ID):
 2    69
1    42
Name: Gender, dtype: int64

# Action units

In [7]:
action_units = pd.read_csv('/Users/dionnespaltman/Desktop/V6/action_units_03-06-2024.csv', sep=',')

In [8]:
display(action_units)

,Unnamed: 0,Frame,Face_id,Confidence,Success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,...,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Stage
0,103,104.0,0.0,0.88,1.0,0.00,0.00,0.00,0.0,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
1,104,105.0,0.0,0.98,1.0,0.00,0.00,0.00,0.0,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
2,111,112.0,0.0,0.98,1.0,0.31,0.59,0.00,0.0,0.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
3,114,115.0,0.0,0.98,1.0,0.00,0.12,0.00,0.0,0.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
4,153,154.0,0.0,0.98,1.0,1.26,1.67,0.00,0.0,0.39,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,80,"[4, 5, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395911,3487088,2196.0,0.0,0.98,1.0,0.62,0.36,0.30,0.0,0.70,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395912,3487089,2197.0,0.0,0.98,1.0,0.63,0.38,0.25,0.0,0.78,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395913,3487090,2198.0,0.0,0.98,1.0,0.69,0.51,0.26,0.0,0.79,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395914,3487091,2199.0,0.0,0.98,1.0,0.67,0.46,0.32,0.0,0.81,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395915,3487092,2200.0,0.0,0.98,1.0,0.62,0.45,0.45,0.0,0.81,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]

In [9]:
# Count the unique IDs in the action_units DataFrame
unique_id_count = action_units['ID'].nunique()

# Display the count of unique IDs
print("Number of unique IDs:", unique_id_count)

Number of unique IDs: 184

In [13]:
# List of IDs to filter
id_list = [80, 87, 78, 92, 38, 129, 95, 118, 49, 94, 39, 93, 79, 81, 48, 119, 114, 57, 146, 113, 50, 45, 106, 42, 101, 74, 130, 73, 99, 66, 33, 125, 61, 34, 122, 43, 100, 44, 107, 112, 51, 115, 140, 35, 60, 123, 32, 98, 124, 131, 72, 136, 75, 46, 41, 102, 142, 117, 54, 145, 53, 65, 30, 62, 37, 121, 134, 77, 88, 133, 67, 111, 144, 52, 116, 143, 40, 103, 47, 104, 132, 71, 135, 76, 36, 63, 120, 31, 64, 127, 91, 69, 96, 29, 83, 84, 138, 58, 85, 139, 82, 28, 97, 68, 59, 108, 25, 23, 24, 26, 27]

# Filter the DataFrame to include only rows with IDs in the specified list
filtered_action_units = action_units[action_units['ID'].isin(id_list)]

# Display the filtered DataFrame
display(filtered_action_units)

,Unnamed: 0,Frame,Face_id,Confidence,Success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,...,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Stage
0,103,104.0,0.0,0.88,1.0,0.00,0.00,0.00,0.0,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
1,104,105.0,0.0,0.98,1.0,0.00,0.00,0.00,0.0,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
2,111,112.0,0.0,0.98,1.0,0.31,0.59,0.00,0.0,0.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
3,114,115.0,0.0,0.98,1.0,0.00,0.12,0.00,0.0,0.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]"
4,153,154.0,0.0,0.98,1.0,1.26,1.67,0.00,0.0,0.39,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,80,"[4, 5, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395911,3487088,2196.0,0.0,0.98,1.0,0.62,0.36,0.30,0.0,0.70,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395912,3487089,2197.0,0.0,0.98,1.0,0.63,0.38,0.25,0.0,0.78,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395913,3487090,2198.0,0.0,0.98,1.0,0.69,0.51,0.26,0.0,0.79,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395914,3487091,2199.0,0.0,0.98,1.0,0.67,0.46,0.32,0.0,0.81,...,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]
3395915,3487092,2200.0,0.0,0.98,1.0,0.62,0.45,0.45,0.0,0.81,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,25,[7]

Average amount of rows per ID:

In [14]:
print(2618540 / 111 )

23590.45045045045

Corresponding to how many minutes of recording time per ID:

In [15]:
print(23590/60/25)

15.726666666666667

# Merge extracted features with filtered donor info

In [36]:
extracted_features = pd.read_csv('/Users/dionnespaltman/Desktop/V6/extracted_features_standardized_03-06-2024.csv', sep=',')
filtered_donor_info =  pd.read_csv('/Users/dionnespaltman/Desktop/V6/filtered_donor_info_03-06-2024.csv', sep=',')

display(extracted_features)
display(filtered_donor_info)

,Unnamed: 0,Frame,Face_id,Confidence,Success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,...,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Stage,Stage_str
0,0,104.0,0.0,0.88,1.0,0.00,0.00,0.00,0.00,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]","[4, 5, 6]"
1,1,105.0,0.0,0.98,1.0,0.00,0.00,0.00,0.00,1.34,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]","[4, 5, 6]"
2,2,112.0,0.0,0.98,1.0,0.31,0.59,0.00,0.00,0.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]","[4, 5, 6]"
3,3,115.0,0.0,0.98,1.0,0.00,0.12,0.00,0.00,0.32,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,80,"[4, 5, 6]","[4, 5, 6]"
4,4,154.0,0.0,0.98,1.0,1.26,1.67,0.00,0.00,0.39,...,0.0,0.0,0.0,1.0,1.0,1.0,0.0,80,"[4, 5, 6]","[4, 5, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2313876,3301669,21069.0,0.0,0.93,1.0,2.08,2.22,0.89,0.16,0.22,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,27,"[4, 5, 6]","[4, 5, 6]"
2313877,3301670,21070.0,0.0,0.93,1.0,2.03,2.14,0.87,0.69,0.27,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,27,"[4, 5, 6]","[4, 5, 6]"
2313878,3301671,21071.0,0.0,0.93,1.0,2.02,2.11,1.12,0.49,0.47,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,27,"[4, 5, 6]","[4, 5, 6]"
2313879,3301672,21072.0,0.0,0.93,1.0,2.43,2.01,1.11,0.65,0.35,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,27,"[4, 5, 6]","[4, 5, 6]"
2313880,3301673,21073.0,0.0,0.93,1.0,2.28,2.35,1.21,0.83,0.36,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,27,"[4, 5, 6]","[4, 5, 6]"

,Unnamed: 0,ID,Stage,Gender,Age,Date,Location,Condition,Weight,Length,...,Nervousness,Physical_sum,Psychological_sum,Sum_VVR,Sum_12,Sum_456,Sum_4567,Sum_1,Sum_2,VVR_group
0,0,23,1.0,2,27.0,2020-08-01,1,2,70.0,160.0,...,2.0,6.0,7.0,13.0,24.0,27.0,37.0,13.0,11.0,0
1,1,23,2.0,2,27.0,2020-08-01,1,2,70.0,160.0,...,2.0,4.0,7.0,11.0,24.0,27.0,37.0,13.0,11.0,0
2,2,23,3.0,2,27.0,2020-08-01,1,2,70.0,160.0,...,2.0,5.0,6.0,11.0,24.0,27.0,37.0,13.0,11.0,0
3,3,23,4.0,2,27.0,2020-08-01,1,2,70.0,160.0,...,2.0,4.0,6.0,10.0,24.0,27.0,37.0,13.0,11.0,0
4,4,23,5.0,2,27.0,2020-08-01,1,2,70.0,160.0,...,1.0,4.0,4.0,8.0,24.0,27.0,37.0,13.0,11.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,705,146,2.0,2,44.0,2021-02-06,0,2,64.0,169.0,...,2.0,4.0,7.0,11.0,22.0,32.0,40.0,11.0,11.0,1
706,706,146,4.0,2,44.0,2021-02-06,0,2,64.0,169.0,...,3.0,4.0,8.0,12.0,22.0,32.0,40.0,11.0,11.0,1
707,707,146,5.0,2,44.0,2021-02-06,0,2,64.0,169.0,...,1.0,5.0,5.0,10.0,22.0,32.0,40.0,11.0,11.0,1
708,708,146,6.0,2,44.0,2021-02-06,0,2,64.0,169.0,...,1.0,5.0,5.0,10.0,22.0,32.0,40.0,11.0,11.0,1
709,709,146,7.0,2,44.0,2021-02-06,0,2,64.0,169.0,...,1.0,4.0,4.0,8.0,22.0,32.0,40.0,11.0,11.0,1

In [34]:
# Merge the DataFrames on the 'ID' column
merged_df = pd.merge(filtered_donor_info, extracted_features, on='ID', how='outer')

# del merged_df
merged_df = merged_df.drop(columns=['Unnamed: 0_x'])

# Display the merged DataFrame
display(merged_df)

,ID,Stage,Gender,Age,Date,Location,Condition,Weight,Length,Faintness,...,AU26_r__standard_deviation,AU26_r__maximum,AU26_r__mean,AU26_r__root_mean_square,AU45_r__sum_values,AU45_r__variance,AU45_r__standard_deviation,AU45_r__maximum,AU45_r__mean,AU45_r__root_mean_square
0,23,1.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,-0.336826,0.44093,-0.608761,-0.600147,-0.356101,0.239263,0.357168,0.546947,0.644834,0.452026
1,23,2.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,-0.336826,0.44093,-0.608761,-0.600147,-0.356101,0.239263,0.357168,0.546947,0.644834,0.452026
2,23,3.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,-0.336826,0.44093,-0.608761,-0.600147,-0.356101,0.239263,0.357168,0.546947,0.644834,0.452026
3,23,4.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,-0.336826,0.44093,-0.608761,-0.600147,-0.356101,0.239263,0.357168,0.546947,0.644834,0.452026
4,23,5.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,-0.336826,0.44093,-0.608761,-0.600147,-0.356101,0.239263,0.357168,0.546947,0.644834,0.452026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,146,2.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,0.688716,0.44093,0.119104,0.454460,1.945159,0.095541,0.249694,0.619122,0.066561,0.182302
706,146,4.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,0.688716,0.44093,0.119104,0.454460,1.945159,0.095541,0.249694,0.619122,0.066561,0.182302
707,146,5.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,0.688716,0.44093,0.119104,0.454460,1.945159,0.095541,0.249694,0.619122,0.066561,0.182302
708,146,6.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,0.688716,0.44093,0.119104,0.454460,1.945159,0.095541,0.249694,0.619122,0.066561,0.182302
709,146,7.0,2,44.0,2021-02-06,0,2,64.0,169.0,1.0,...,0.688716,0.44093,0.119104,0.454460,1.945159,0.095541,0.249694,0.619122,0.066561,0.182302

In [35]:
merged_df.to_csv('/Users/dionnespaltman/Desktop/V6/merged_df_03-06-2024.csv', sep=',')