# Descriptives

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
donor_info = pd.read_csv('/Users/dionnespaltman/Desktop/V6/filtered_donor_info_11-06-2024.csv', sep=',')

if 'Unnamed: 0' in donor_info.columns:
    donor_info.drop(columns=['Unnamed: 0'], inplace=True)

display(donor_info)

,ID,Stage,Gender,Age,Date,Location,Condition,Weight,Length,Faintness,...,Nervousness,Physical_sum,Psychological_sum,Sum_VVR,Sum_12,Sum_456,Sum_4567,Sum_1,Sum_2,VVR_group
0,7,1.0,2,25.0,2019-10-28,0,2,71.0,172.0,1.0,...,2.0,5.0,6.0,11.0,23.0,65.0,77.0,11.0,12.0,1
1,7,2.0,2,25.0,2019-10-28,0,2,71.0,172.0,1.0,...,3.0,4.0,8.0,12.0,23.0,65.0,77.0,11.0,12.0,1
2,7,3.0,2,25.0,2019-10-28,0,2,71.0,172.0,1.0,...,2.0,4.0,7.0,11.0,23.0,65.0,77.0,11.0,12.0,1
3,7,4.0,2,25.0,2019-10-28,0,2,71.0,172.0,2.0,...,2.0,5.0,6.0,11.0,23.0,65.0,77.0,11.0,12.0,1
4,7,5.0,2,25.0,2019-10-28,0,2,71.0,172.0,1.0,...,4.0,5.0,9.0,14.0,23.0,65.0,77.0,11.0,12.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1774,331,2.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,4.0,4.0,10.0,14.0,28.0,30.0,38.0,14.0,14.0,0
1775,331,4.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,2.0,4.0,8.0,12.0,28.0,30.0,38.0,14.0,14.0,0
1776,331,5.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,1.0,6.0,4.0,10.0,28.0,30.0,38.0,14.0,14.0,0
1777,331,6.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,1.0,4.0,4.0,8.0,28.0,30.0,38.0,14.0,14.0,0
1778,331,7.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,1.0,4.0,4.0,8.0,28.0,30.0,38.0,14.0,14.0,0

In [4]:
# Ensure each ID is unique by dropping duplicates based on 'ID'
unique_donor_info = donor_info.drop_duplicates(subset='ID')

display(unique_donor_info)

,ID,Stage,Gender,Age,Date,Location,Condition,Weight,Length,Faintness,...,Nervousness,Physical_sum,Psychological_sum,Sum_VVR,Sum_12,Sum_456,Sum_4567,Sum_1,Sum_2,VVR_group
0,7,1.0,2,25.0,2019-10-28,0,2,71.0,172.0,1.0,...,2.0,5.0,6.0,11.0,23.0,65.0,77.0,11.0,12.0,1
7,23,1.0,2,27.0,2020-08-01,1,2,70.0,160.0,1.0,...,2.0,6.0,7.0,13.0,24.0,27.0,37.0,13.0,11.0,0
14,24,1.0,2,25.0,2020-01-22,1,2,96.0,174.0,1.0,...,3.0,4.0,8.0,12.0,23.0,28.0,37.0,12.0,11.0,0
21,25,1.0,2,25.0,2020-05-02,1,2,68.0,169.0,1.0,...,3.0,4.0,12.0,16.0,28.0,33.0,44.0,16.0,12.0,1
28,26,1.0,1,35.0,2020-06-02,2,1,88.0,187.0,2.0,...,2.0,7.0,8.0,15.0,30.0,29.0,37.0,15.0,15.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1749,323,1.0,2,39.0,2022-10-26,3,3,63.0,163.0,1.0,...,1.0,4.0,5.0,9.0,18.0,25.0,35.0,9.0,9.0,0
1755,325,1.0,2,25.0,2022-07-11,3,3,66.0,170.0,1.0,...,2.0,4.0,8.0,12.0,22.0,28.0,36.0,12.0,10.0,0
1761,329,1.0,2,59.0,2022-11-28,3,3,75.0,168.0,1.0,...,1.0,4.0,6.0,10.0,18.0,27.0,35.0,10.0,8.0,0
1767,330,1.0,2,49.0,2022-11-30,0,3,80.0,177.0,1.0,...,2.0,4.0,7.0,11.0,23.0,26.0,35.0,11.0,12.0,0
1773,331,1.0,2,56.0,2022-11-30,0,3,73.0,167.0,1.0,...,3.0,4.0,10.0,14.0,28.0,30.0,38.0,14.0,14.0,0

In [5]:
unique_donor_list = list(unique_donor_info['ID'])
print(unique_donor_list)
print(len(unique_donor_list))

[7, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 321, 322, 323, 325, 329, 330, 331]
278

# Get the range of dates

In [6]:
# Find the first and last dates
first_date = unique_donor_info['Date'].min()
last_date = unique_donor_info['Date'].max()

print("First date:", first_date)
print("Last date:", last_date)

First date: 2019-10-28
Last date: 2022-12-09

# Counts

In [7]:
# Count occurrences of VVR_group
vvr_group_counts = unique_donor_info['VVR_group'].value_counts()
print("\nVVR_group counts (per unique ID):\n", vvr_group_counts)

# Count occurrences of Condition
condition_counts = unique_donor_info['Condition'].value_counts()
print("\nCondition counts (per unique ID):\n", condition_counts)

# Count occurrences of Gender
gender_counts = unique_donor_info['Gender'].value_counts()
print("\nGender counts (per unique ID):\n", gender_counts)

VVR_group counts (per unique ID):
 0    186
1     92
Name: VVR_group, dtype: int64

Condition counts (per unique ID):
 3    152
1     78
2     48
Name: Condition, dtype: int64

Gender counts (per unique ID):
 2    163
1    115
Name: Gender, dtype: int64

# Action units

In [8]:
action_units = pd.read_csv('/Users/dionnespaltman/Desktop/V6/extracted_features_standardized_11-06-2024.csv', sep=',')

if 'Unnamed: 0' in action_units.columns:
    action_units.drop(columns=['Unnamed: 0'], inplace=True)

filtered_action_units = action_units[action_units['ID'].isin(unique_donor_list)]

In [9]:
display(filtered_action_units)

,AU01_r__sum_values,AU01_r__variance,AU01_r__standard_deviation,AU01_r__maximum,AU01_r__mean,AU01_r__root_mean_square,AU02_r__sum_values,AU02_r__variance,AU02_r__standard_deviation,AU02_r__maximum,...,AU26_r__maximum,AU26_r__mean,AU26_r__root_mean_square,AU45_r__sum_values,AU45_r__variance,AU45_r__standard_deviation,AU45_r__maximum,AU45_r__mean,AU45_r__root_mean_square,ID
0,-0.975651,-0.563311,-0.510278,0.293698,-0.788277,-0.598878,-0.144794,0.396952,0.619636,0.587102,...,0.425279,-0.786613,-0.696839,0.520966,1.700927,1.712210,0.830151,1.741972,1.745418,7
1,-1.308169,-0.495347,-0.425249,0.293698,-0.703835,-0.513168,-1.253416,-0.457713,-0.468309,-0.299198,...,0.425279,-0.642748,-0.651193,-0.504468,0.296375,0.440450,0.760722,1.243173,0.665506,23
2,-0.036281,-0.309096,-0.203131,0.293698,-0.522833,-0.299689,0.599984,0.340599,0.558079,0.712437,...,0.425279,3.132948,2.795771,0.129283,-0.279627,-0.201661,0.014352,-0.478731,-0.279724,24
3,-0.794137,0.070108,0.209241,-0.123704,-0.075155,0.126844,-1.262475,-0.649186,-0.783197,-0.827396,...,0.425279,0.394186,0.499951,-0.587993,0.094357,0.226315,-0.645230,0.514820,0.302852,25
4,-0.003186,0.960643,1.035507,0.293698,0.962762,1.025016,-1.150346,-0.569627,-0.647296,-0.684156,...,0.425279,-0.951628,-0.731221,-1.239117,-0.246984,-0.162414,0.639220,-1.034420,-0.377156,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,0.560309,1.292514,1.307951,0.293698,1.423453,1.358268,0.062691,0.305871,0.519611,-0.057480,...,-0.162826,-0.846163,-0.845794,-0.142084,0.642278,0.784992,0.864866,0.560518,0.737070,323
279,-0.770033,-0.475306,-0.400607,0.293698,-0.707798,-0.495818,-0.510360,-0.424359,-0.417336,0.220049,...,0.425279,-1.669019,-1.846330,-0.586609,-0.362405,-0.303044,0.326786,-0.488608,-0.360082,325
280,-2.481632,2.555959,2.229726,-0.851482,-2.156568,1.410758,-1.602085,3.679330,3.236393,-0.433485,...,3.521479,0.610696,0.169932,-2.381393,4.280036,3.507346,0.517718,2.061400,3.218211,329
281,-1.506718,-1.472349,-2.044681,-1.707691,-1.555252,-1.933354,-1.350571,-0.969846,-1.445085,-1.740553,...,-3.328215,-1.706598,-1.845208,-0.958863,-0.594948,-0.603916,-0.315439,-0.770324,-0.661360,330
282,1.358600,4.346119,3.328799,0.625479,3.176498,3.330533,2.435059,7.282817,5.201104,0.819867,...,0.425279,-1.779581,0.208143,0.696288,6.381711,4.701091,4.440496,2.616941,4.291136,331

In [10]:
# Count the unique IDs in the action_units DataFrame
unique_id_count = filtered_action_units['ID'].nunique()

# Display the count of unique IDs
print("Number of unique IDs:", unique_id_count)

Number of unique IDs: 278

In [11]:
print(filtered_action_units.shape)

(278, 103)

# Check NaN values

In [12]:
nan_counts = unique_donor_info.isna().sum()
print(nan_counts)

ID                   0
Stage                0
Gender               0
Age                  2
Date                 0
Location             0
Condition            0
Weight               2
Length               2
Faintness            0
Dizziness            0
Weakness             0
Lightheadedness      0
Fear                 0
Tension              0
Stress               0
Nervousness          1
Physical_sum         0
Psychological_sum    0
Sum_VVR              0
Sum_12               0
Sum_456              0
Sum_4567             0
Sum_1                0
Sum_2                0
VVR_group            0
dtype: int64

In [13]:
columns_to_drop = ['Age', 'Weight', 'Length', 'Nervousness'] 

unique_donor_info = unique_donor_info.drop(columns_to_drop, axis=1)

In [14]:
nan_counts = unique_donor_info.isna().sum()
print(nan_counts)

ID                   0
Stage                0
Gender               0
Date                 0
Location             0
Condition            0
Faintness            0
Dizziness            0
Weakness             0
Lightheadedness      0
Fear                 0
Tension              0
Stress               0
Physical_sum         0
Psychological_sum    0
Sum_VVR              0
Sum_12               0
Sum_456              0
Sum_4567             0
Sum_1                0
Sum_2                0
VVR_group            0
dtype: int64

In [15]:
nan_counts = filtered_action_units.isna().sum()
print(nan_counts)

AU01_r__sum_values            0
AU01_r__variance              0
AU01_r__standard_deviation    0
AU01_r__maximum               0
AU01_r__mean                  0
                             ..
AU45_r__standard_deviation    0
AU45_r__maximum               0
AU45_r__mean                  0
AU45_r__root_mean_square      0
ID                            0
Length: 103, dtype: int64

# Merge extracted features with filtered donor info

In [16]:
# Merge the DataFrames on the 'ID' column
merged_df = pd.merge(unique_donor_info, filtered_action_units, on='ID', how='left')

# del merged_df

# Display the merged DataFrame
display(merged_df)

print(merged_df.columns)

,ID,Stage,Gender,Date,Location,Condition,Faintness,Dizziness,Weakness,Lightheadedness,...,AU26_r__standard_deviation,AU26_r__maximum,AU26_r__mean,AU26_r__root_mean_square,AU45_r__sum_values,AU45_r__variance,AU45_r__standard_deviation,AU45_r__maximum,AU45_r__mean,AU45_r__root_mean_square
0,7,1.0,2,2019-10-28,0,2,1.0,1.0,1.0,2.0,...,-0.585935,0.425279,-0.786613,-0.696839,0.520966,1.700927,1.712210,0.830151,1.741972,1.745418
1,23,1.0,2,2020-08-01,1,2,1.0,2.0,2.0,1.0,...,-0.624259,0.425279,-0.642748,-0.651193,-0.504468,0.296375,0.440450,0.760722,1.243173,0.665506
2,24,1.0,2,2020-01-22,1,2,1.0,1.0,1.0,1.0,...,2.367560,0.425279,3.132948,2.795771,0.129283,-0.279627,-0.201661,0.014352,-0.478731,-0.279724
3,25,1.0,2,2020-05-02,1,2,1.0,1.0,1.0,1.0,...,0.584439,0.425279,0.394186,0.499951,-0.587993,0.094357,0.226315,-0.645230,0.514820,0.302852
4,26,1.0,1,2020-06-02,2,1,2.0,2.0,2.0,1.0,...,-0.517633,0.425279,-0.951628,-0.731221,-1.239117,-0.246984,-0.162414,0.639220,-1.034420,-0.377156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,323,1.0,2,2022-10-26,3,3,1.0,1.0,1.0,1.0,...,-0.804403,-0.162826,-0.846163,-0.845794,-0.142084,0.642278,0.784992,0.864866,0.560518,0.737070
274,325,1.0,2,2022-07-11,3,3,1.0,1.0,1.0,1.0,...,-1.926084,0.425279,-1.669019,-1.846330,-0.586609,-0.362405,-0.303044,0.326786,-0.488608,-0.360082
275,329,1.0,2,2022-11-28,3,3,1.0,1.0,1.0,1.0,...,-0.266200,3.521479,0.610696,0.169932,-2.381393,4.280036,3.507346,0.517718,2.061400,3.218211
276,330,1.0,2,2022-11-30,0,3,1.0,1.0,1.0,1.0,...,-1.889172,-3.328215,-1.706598,-1.845208,-0.958863,-0.594948,-0.603916,-0.315439,-0.770324,-0.661360
277,331,1.0,2,2022-11-30,0,3,1.0,1.0,1.0,1.0,...,1.340280,0.425279,-1.779581,0.208143,0.696288,6.381711,4.701091,4.440496,2.616941,4.291136

Index(['ID', 'Stage', 'Gender', 'Date', 'Location', 'Condition', 'Faintness',
       'Dizziness', 'Weakness', 'Lightheadedness',
       ...
       'AU26_r__standard_deviation', 'AU26_r__maximum', 'AU26_r__mean',
       'AU26_r__root_mean_square', 'AU45_r__sum_values', 'AU45_r__variance',
       'AU45_r__standard_deviation', 'AU45_r__maximum', 'AU45_r__mean',
       'AU45_r__root_mean_square'],
      dtype='object', length=124)

In [17]:
nan_counts = merged_df.isna().sum()
print(nan_counts)

ID                            0
Stage                         0
Gender                        0
Date                          0
Location                      0
                             ..
AU45_r__variance              0
AU45_r__standard_deviation    0
AU45_r__maximum               0
AU45_r__mean                  0
AU45_r__root_mean_square      0
Length: 124, dtype: int64

In [24]:
merged_df.to_csv('/Users/dionnespaltman/Desktop/V6/merged_df_11-06-2024.csv', sep=',')

# Action units

In [9]:
action_units = pd.read_csv('/Users/dionnespaltman/Desktop/V6/action_units_11-06-2024.csv', sep=',')

if 'Unnamed: 0' in action_units.columns:
    action_units.drop(columns=['Unnamed: 0'], inplace=True)

display(action_units)

,Frame,Face_id,Confidence,Success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,...,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Stage
0,20.0,0.0,0.88,1.0,0.43,0.05,0.02,0.0,0.80,0.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
1,21.0,0.0,0.88,1.0,0.43,0.05,0.11,0.0,1.26,1.11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
2,22.0,0.0,0.88,1.0,0.20,0.02,0.09,0.0,0.90,0.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
3,59.0,0.0,0.98,1.0,0.14,0.47,0.13,0.0,1.22,0.35,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
4,60.0,0.0,0.98,1.0,0.14,0.78,0.21,0.0,1.98,0.47,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6561949,24371.0,0.0,0.98,1.0,0.87,0.00,0.04,0.0,1.87,1.86,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561950,24372.0,0.0,0.98,1.0,0.92,0.00,0.00,0.0,2.05,2.09,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561951,24373.0,0.0,0.98,1.0,0.82,0.00,0.00,0.0,2.19,2.26,...,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561952,24374.0,0.0,0.98,1.0,0.71,0.00,0.00,0.0,2.28,2.31,...,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561953,24375.0,0.0,0.98,1.0,0.50,0.00,0.00,0.0,2.31,2.37,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"

In [10]:
# Count the occurrences of each ID
id_counts = action_units['ID'].value_counts().reset_index()
id_counts.columns = ['ID', 'Count']

# Sort the list from lowest count to highest count
sorted_id_counts = id_counts.sort_values(by='Count')

print(sorted_id_counts)

      ID  Count
282  148   2138
281  329   2731
280  303   3441
279  105   6972
278  179   7610
..   ...    ...
4    146  37832
3    228  38056
2    291  38192
1    128  40359
0    178  40795

[283 rows x 2 columns]

In [13]:
unique_id_list = [
 7, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
 52, 53, 54, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
 85, 87, 88, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116,
 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 216,
 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240,
 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 278, 279,
 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303,
 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 321, 322, 323, 325, 329, 330, 331
]

print(len(unique_id_list))

278

In [14]:
filtered_action_units = action_units[action_units['ID'].isin(unique_id_list)]

In [16]:
display(filtered_action_units)

,Frame,Face_id,Confidence,Success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,...,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Stage
0,20.0,0.0,0.88,1.0,0.43,0.05,0.02,0.0,0.80,0.79,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
1,21.0,0.0,0.88,1.0,0.43,0.05,0.11,0.0,1.26,1.11,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
2,22.0,0.0,0.88,1.0,0.20,0.02,0.09,0.0,0.90,0.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
3,59.0,0.0,0.98,1.0,0.14,0.47,0.13,0.0,1.22,0.35,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
4,60.0,0.0,0.98,1.0,0.14,0.78,0.21,0.0,1.98,0.47,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,100,"[4, 5, 6]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6561949,24371.0,0.0,0.98,1.0,0.87,0.00,0.04,0.0,1.87,1.86,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561950,24372.0,0.0,0.98,1.0,0.92,0.00,0.00,0.0,2.05,2.09,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561951,24373.0,0.0,0.98,1.0,0.82,0.00,0.00,0.0,2.19,2.26,...,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561952,24374.0,0.0,0.98,1.0,0.71,0.00,0.00,0.0,2.28,2.31,...,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"
6561953,24375.0,0.0,0.98,1.0,0.50,0.00,0.00,0.0,2.31,2.37,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,99,"[4, 5, 6]"

In [17]:
# Frames per participant
print(6467627/278)

23264.845323741007

In [18]:
# Seconds per participant
print(23264.845323741007/60)

387.7474220623501

In [23]:
# Minutes per participant 
print(387.7474220623501/60)

# Seconds 
print(387.7474220623501 - (6*60))

6.462457034372502
27.747422062350097

In [15]:
# Count the occurrences of each ID
id_counts = filtered_action_units['ID'].value_counts().reset_index()
id_counts.columns = ['ID', 'Count']

# Sort the list from lowest count to highest count
sorted_id_counts = id_counts.sort_values(by='Count')

print(sorted_id_counts)

      ID  Count
277  148   2138
276  329   2731
275  303   3441
274  179   7610
273   23  14667
..   ...    ...
4    146  37832
3    228  38056
2    291  38192
1    128  40359
0    178  40795

[278 rows x 2 columns]

# Count VVR group per condition

In [19]:
print(list(merged_df.columns))
display(merged_df)

['ID', 'Stage', 'Gender', 'Date', 'Location', 'Condition', 'Faintness', 'Dizziness', 'Weakness', 'Lightheadedness', 'Fear', 'Tension', 'Stress', 'Physical_sum', 'Psychological_sum', 'Sum_VVR', 'Sum_12', 'Sum_456', 'Sum_4567', 'Sum_1', 'Sum_2', 'VVR_group', 'AU01_r__sum_values', 'AU01_r__variance', 'AU01_r__standard_deviation', 'AU01_r__maximum', 'AU01_r__mean', 'AU01_r__root_mean_square', 'AU02_r__sum_values', 'AU02_r__variance', 'AU02_r__standard_deviation', 'AU02_r__maximum', 'AU02_r__mean', 'AU02_r__root_mean_square', 'AU04_r__sum_values', 'AU04_r__variance', 'AU04_r__standard_deviation', 'AU04_r__maximum', 'AU04_r__mean', 'AU04_r__root_mean_square', 'AU05_r__sum_values', 'AU05_r__variance', 'AU05_r__standard_deviation', 'AU05_r__maximum', 'AU05_r__mean', 'AU05_r__root_mean_square', 'AU06_r__sum_values', 'AU06_r__variance', 'AU06_r__standard_deviation', 'AU06_r__maximum', 'AU06_r__mean', 'AU06_r__root_mean_square', 'AU07_r__sum_values', 'AU07_r__variance', 'AU07_r__standard_deviation', 'AU07_r__maximum', 'AU07_r__mean', 'AU07_r__root_mean_square', 'AU09_r__sum_values', 'AU09_r__variance', 'AU09_r__standard_deviation', 'AU09_r__maximum', 'AU09_r__mean', 'AU09_r__root_mean_square', 'AU10_r__sum_values', 'AU10_r__variance', 'AU10_r__standard_deviation', 'AU10_r__maximum', 'AU10_r__mean', 'AU10_r__root_mean_square', 'AU12_r__sum_values', 'AU12_r__variance', 'AU12_r__standard_deviation', 'AU12_r__maximum', 'AU12_r__mean', 'AU12_r__root_mean_square', 'AU14_r__sum_values', 'AU14_r__variance', 'AU14_r__standard_deviation', 'AU14_r__maximum', 'AU14_r__mean', 'AU14_r__root_mean_square', 'AU15_r__sum_values', 'AU15_r__variance', 'AU15_r__standard_deviation', 'AU15_r__maximum', 'AU15_r__mean', 'AU15_r__root_mean_square', 'AU17_r__sum_values', 'AU17_r__variance', 'AU17_r__standard_deviation', 'AU17_r__maximum', 'AU17_r__mean', 'AU17_r__root_mean_square', 'AU20_r__sum_values', 'AU20_r__variance', 'AU20_r__standard_deviation', 'AU20_r__maximum', 'AU20_r__mean', 'AU20_r__root_mean_square', 'AU23_r__sum_values', 'AU23_r__variance', 'AU23_r__standard_deviation', 'AU23_r__maximum', 'AU23_r__mean', 'AU23_r__root_mean_square', 'AU25_r__sum_values', 'AU25_r__variance', 'AU25_r__standard_deviation', 'AU25_r__maximum', 'AU25_r__mean', 'AU25_r__root_mean_square', 'AU26_r__sum_values', 'AU26_r__variance', 'AU26_r__standard_deviation', 'AU26_r__maximum', 'AU26_r__mean', 'AU26_r__root_mean_square', 'AU45_r__sum_values', 'AU45_r__variance', 'AU45_r__standard_deviation', 'AU45_r__maximum', 'AU45_r__mean', 'AU45_r__root_mean_square']

,ID,Stage,Gender,Date,Location,Condition,Faintness,Dizziness,Weakness,Lightheadedness,...,AU26_r__standard_deviation,AU26_r__maximum,AU26_r__mean,AU26_r__root_mean_square,AU45_r__sum_values,AU45_r__variance,AU45_r__standard_deviation,AU45_r__maximum,AU45_r__mean,AU45_r__root_mean_square
0,7,1.0,2,2019-10-28,0,2,1.0,1.0,1.0,2.0,...,-0.585935,0.425279,-0.786613,-0.696839,0.520966,1.700927,1.712210,0.830151,1.741972,1.745418
1,23,1.0,2,2020-08-01,1,2,1.0,2.0,2.0,1.0,...,-0.624259,0.425279,-0.642748,-0.651193,-0.504468,0.296375,0.440450,0.760722,1.243173,0.665506
2,24,1.0,2,2020-01-22,1,2,1.0,1.0,1.0,1.0,...,2.367560,0.425279,3.132948,2.795771,0.129283,-0.279627,-0.201661,0.014352,-0.478731,-0.279724
3,25,1.0,2,2020-05-02,1,2,1.0,1.0,1.0,1.0,...,0.584439,0.425279,0.394186,0.499951,-0.587993,0.094357,0.226315,-0.645230,0.514820,0.302852
4,26,1.0,1,2020-06-02,2,1,2.0,2.0,2.0,1.0,...,-0.517633,0.425279,-0.951628,-0.731221,-1.239117,-0.246984,-0.162414,0.639220,-1.034420,-0.377156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,323,1.0,2,2022-10-26,3,3,1.0,1.0,1.0,1.0,...,-0.804403,-0.162826,-0.846163,-0.845794,-0.142084,0.642278,0.784992,0.864866,0.560518,0.737070
274,325,1.0,2,2022-07-11,3,3,1.0,1.0,1.0,1.0,...,-1.926084,0.425279,-1.669019,-1.846330,-0.586609,-0.362405,-0.303044,0.326786,-0.488608,-0.360082
275,329,1.0,2,2022-11-28,3,3,1.0,1.0,1.0,1.0,...,-0.266200,3.521479,0.610696,0.169932,-2.381393,4.280036,3.507346,0.517718,2.061400,3.218211
276,330,1.0,2,2022-11-30,0,3,1.0,1.0,1.0,1.0,...,-1.889172,-3.328215,-1.706598,-1.845208,-0.958863,-0.594948,-0.603916,-0.315439,-0.770324,-0.661360
277,331,1.0,2,2022-11-30,0,3,1.0,1.0,1.0,1.0,...,1.340280,0.425279,-1.779581,0.208143,0.696288,6.381711,4.701091,4.440496,2.616941,4.291136

In [20]:
# Create the table that shows the count of participants in each group
group_counts = merged_df.groupby(['Condition', 'VVR_group']).size().reset_index(name='Count')

print(group_counts)

   Condition  VVR_group  Count
0          1          0     66
1          1          1     12
2          2          0     18
3          2          1     30
4          3          0    102
5          3          1     50