# Next steps

In this file, I am going to the use the following files: 
- extracted_features_clean_imcomplete: dataframe, has all of the information in it (TSfresh)
- faint_info_file: this has the questionnaire data

In [4]:
# import 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle

# Import the files we need

In [8]:
file_path = '/Users/dionnespaltman/Desktop/downloading_new/faint_info_final.csv'

# Read the pickle file into a DataFrame
donor_info = pd.read_csv(file_path)

# Display the DataFrame
display(donor_info)

,Unnamed: 0,ID,Time_point,Gender,Age,Datum,Location,Condition,Weight,Length,...,Weaknessn,Lightheadednessn,Fearn,Tensionn,Stressn,Nervousnessn,na.rm,sumVVR_total,sumVVR_456,VVR_group
0,0,5,-1.0,2,33.0,21-10-2019,0,1,74.0,171.0,...,1.0,1.0,2.0,2.0,2.0,2.0,True,66.0,26.0,0
1,1,6,-1.0,1,33.0,25-10-2019,0,2,86.0,176.0,...,1.0,1.0,1.0,1.0,1.0,1.0,True,56.0,24.0,0
2,2,7,-1.0,2,25.0,28-10-2019,0,2,71.0,172.0,...,1.0,2.0,1.0,2.0,1.0,2.0,True,111.0,65.0,1
3,3,8,-1.0,1,56.0,30-10-2019,0,1,87.0,178.0,...,1.0,1.0,1.0,2.0,1.0,1.0,True,57.0,24.0,0
4,4,9,-1.0,1,41.0,31-10-2019,0,1,80.0,175.0,...,1.0,1.0,1.0,1.0,1.0,1.0,True,56.0,24.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,328,-1.0,2,33.0,23-11-2022,3,3,55.0,157.0,...,1.0,1.0,1.0,2.0,1.0,2.0,True,55.0,27.0,0
316,316,329,-1.0,2,59.0,28-11-2022,3,3,75.0,168.0,...,1.0,1.0,1.0,2.0,2.0,1.0,True,53.0,27.0,0
317,317,330,-1.0,2,49.0,30-11-2022,0,3,80.0,177.0,...,1.0,1.0,2.0,2.0,1.0,2.0,True,58.0,26.0,0
318,318,331,-1.0,2,56.0,30-11-2022,0,3,73.0,167.0,...,1.0,1.0,1.0,4.0,2.0,3.0,True,66.0,30.0,0
319,319,332,-1.0,2,21.0,19-12-2022,3,2,66.0,173.0,...,1.0,1.0,3.0,2.0,2.0,3.0,True,87.0,47.0,1

In [4]:
file_path = '/Users/dionnespaltman/Desktop/downloading/dummy_df.pkl'

# Read the pickle file into a DataFrame
dummy = pd.read_pickle(file_path)

# Display the DataFrame
display(dummy)

,frame,face_id,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU07_r,...,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c,ID,Timeframe
0,18082,0.0,0.98,1.0,0.00,0.00,0.27,0.00,0.08,0.07,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,10,[3]
1,105,0.0,0.98,1.0,0.57,0.74,1.48,0.00,1.09,0.43,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,10,[3]
2,13428,0.0,0.98,1.0,0.00,0.00,0.79,0.00,0.00,0.15,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,10,[3]
3,855,0.0,0.98,1.0,0.00,0.00,0.55,0.00,0.03,0.00,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,10,[7]
4,19440,0.0,0.98,1.0,1.07,0.73,1.30,0.00,0.00,0.04,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,10,[3]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179669,1602,0.0,0.88,1.0,0.00,0.00,0.00,0.00,1.06,0.57,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,99,"[4, 5, 6]"
179670,14605,0.0,0.98,1.0,0.00,0.00,0.00,0.03,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,99,"[4, 5, 6]"
179671,1187,0.0,0.98,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,[7]
179672,1044,0.0,0.98,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,[7]
179673,1165,0.0,0.98,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,[7]

# Merging files

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Reset the index of donor_info and create 'ID' as a column
donor_info.reset_index(drop=True, inplace=True)

print(donor_info['ID'])

# Ensure 'ID' column is in the same data type in both DataFrames
donor_info['ID'] = donor_info['ID'].astype(str)

# Concatenate features and labels along the columns axis
combined_data = pd.concat([dummy.set_index('ID'), donor_info.set_index('ID')], axis=1, join='inner')

# Define features (X) and labels (y)
X = combined_data.drop('condition', axis=1)  # Assuming 'Condition' is the label
y = combined_data['condition']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)